version: 2.1
jobs:
  build:
     machine: true
     working_directory: ~/nginx-apigw
     steps:
       - checkout
       - setup_remote_docker:
           docker_layer_caching: true
       - run: |
           echo "$BASE64_GITCRYPT_KEY" | base64 -d > git-crypt.key
           docker run --rm -it \
               -v "git-crypt.key:/app/key/gpg-private.asc" \
               -v ".:/app/repo" \
               sunzhongmou/git-crypt \
               git-crypt unlock

       - run: |
           make build
           make push
