version: 2.1
jobs:
  build:
     machine: true
     working_directory: ~/nginx-apigw
     steps:
       - checkout
       - run: |
           echo "$BASE64_GITCRYPT_KEY" | base64 -d > git-crypt.key
           echo git-crypt.key
           docker create -v /app/repo --name repo alpine:3.4 /bin/true
           docker cp ./ repo:/app/repo
           docker create -v /app/key --name key alpine:3.4 /bin/true
           docker cp git-crypt.key key:/app/key/gpg-private.asc
           docker run --rm -it \
               --volumes-from key \
               --volumes-from repo \
               sunzhongmou/git-crypt \
               git-crypt unlock
           docker cp repo:/app/repo/secrets/docker-hub.env secrets/docker-hub.env
           docker cp repo:/app/repo/secrets/heroku.env secrets/heroku.env

       - run: |
           make build
           make push
           make deploy
           curl https://cli-assets.heroku.com/install.sh | sh
           heroku container:release web --app oneapi-stg
