version: 2.1
jobs:
  build:
     machine: true
     working_directory: ~/nginx-apigw
     steps:
       - checkout
       - run: |
           echo "$BASE64_GITCRYPT_KEY" | base64 -d > git-crypt.key
           docker create -v /app/repo --name configs alpine:3.4 /bin/true
           docker cp ./ configs:/app/repo
           docker run --rm -it \
               -v "git-crypt.key:/app/key/gpg-private.asc" \
               --volumes-from configs \
               sunzhongmou/git-crypt \
               git-crypt unlock

       - run: |
           make build
           make push
